-- CreateTable
CREATE TABLE "USER" (
    "ID" TEXT NOT NULL,
    "PW" TEXT NOT NULL,
    "FAM_ID" TEXT NOT NULL,
    "PHONE" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "AGE" INTEGER NOT NULL,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "FAMILY" (
    "ID" TEXT NOT NULL,
    "ADDRESS" TEXT NOT NULL,

    CONSTRAINT "FAMILY_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "BOOKS" (
    "ISBN" TEXT NOT NULL,
    "TITLE" TEXT NOT NULL,
    "AUTHOR" TEXT,
    "PUBLISHER" TEXT,
    "QUANTITY" INTEGER NOT NULL,
    "IMG_URL" TEXT NOT NULL,

    CONSTRAINT "BOOKS_pkey" PRIMARY KEY ("ISBN")
);

-- CreateTable
CREATE TABLE "BOOK_STATUS" (
    "ISBN" TEXT NOT NULL,
    "STATUS_LEVEL" INTEGER NOT NULL,
    "LOST" BOOLEAN NOT NULL,
    "DAMAGED" BOOLEAN NOT NULL,

    CONSTRAINT "BOOK_STATUS_pkey" PRIMARY KEY ("ISBN")
);

-- CreateTable
CREATE TABLE "CHECKOUT_STATUS" (
    "CHECK_NUMBER" TEXT NOT NULL,
    "CHECK_USER" TEXT NOT NULL,
    "CHECK_BOOK" TEXT NOT NULL,
    "CHECK_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CHECKOUT_STATUS_pkey" PRIMARY KEY ("CHECK_NUMBER")
);

-- CreateTable
CREATE TABLE "RESERVE_LIST" (
    "RSV_NUM" TEXT NOT NULL,
    "RSV_BOOK" TEXT NOT NULL,
    "RSV_USER" TEXT NOT NULL,
    "RSV_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RESERVE_LIST_pkey" PRIMARY KEY ("RSV_NUM")
);

-- CreateTable
CREATE TABLE "DELAY_LIST" (
    "DLY_NUM" TEXT NOT NULL,
    "DLY_BOOK" TEXT NOT NULL,
    "DLY_USER" TEXT NOT NULL,
    "EXP_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DELAY_LIST_pkey" PRIMARY KEY ("DLY_NUM")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_FAM_ID_key" ON "USER"("FAM_ID");

-- CreateIndex
CREATE UNIQUE INDEX "CHECKOUT_STATUS_CHECK_USER_key" ON "CHECKOUT_STATUS"("CHECK_USER");

-- CreateIndex
CREATE UNIQUE INDEX "CHECKOUT_STATUS_CHECK_BOOK_key" ON "CHECKOUT_STATUS"("CHECK_BOOK");

-- AddForeignKey
ALTER TABLE "USER" ADD CONSTRAINT "USER_FAM_ID_fkey" FOREIGN KEY ("FAM_ID") REFERENCES "FAMILY"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOK_STATUS" ADD CONSTRAINT "BOOK_STATUS_ISBN_fkey" FOREIGN KEY ("ISBN") REFERENCES "BOOKS"("ISBN") ON DELETE RESTRICT ON UPDATE CASCADE;
