// import "./globals.css";

export const metadata = {
  title: "유일도서관",
  description: "Generated by jshe1207",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
